# Generated by Django 4.2.5 on 2023-09-16 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_name', models.CharField(max_length=200)),
                ('final_field_1', models.CharField(max_length=200)),
                ('final_field_2', models.CharField(max_length=200)),
                ('final_field_3', models.CharField(max_length=200)),
                ('final_field_4', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarifProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('field_1', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field_2', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field_3', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('field_4', models.IntegerField(choices=[(1, 'Включено'), (2, 'Не включено')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tarif_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarif')),
            ],
            options={
                'verbose_name': 'ServiceTariff',
                'verbose_name_plural': 'ServiceTariffs',
                'db_table': 'serviceTariff',
            },
        ),
    ]
